/** @type {import('tailwindcss').Config} */
/**
 * Stitch (EthicalFinder / Hawalay) — shared design tokens from Stitch HTML.
 * Pages use Tailwind utilities generated from this config + `src/index.css` globals.
 */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#4edea3',
        'on-tertiary': '#ffffff',
        'on-surface': '#191c1d',
        'primary-container': '#10b981',
        outline: '#6c7a71',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#ffddb8',
        'primary-fixed-dim': '#4edea3',
        'secondary-fixed': '#89f5e7',
        'on-primary': '#ffffff',
        'surface-bright': '#f8f9fa',
        'on-error': '#ffffff',
        surface: '#f8f9fa',
        background: '#f8f9fa',
        'inverse-on-surface': '#f0f1f2',
        'tertiary-fixed-dim': '#ffb95f',
        'surface-container-high': '#e7e8e9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'on-background': '#191c1d',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#005049',
        'outline-variant': '#bbcabf',
        'on-secondary-container': '#006f66',
        primary: '#006c49',
        'on-tertiary-fixed': '#2a1700',
        'inverse-surface': '#2e3132',
        'secondary-container': '#86f2e4',
        'surface-container': '#edeeef',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#523200',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#3c4a42',
        'surface-variant': '#e1e3e4',
        'primary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#6bd8cb',
        'tertiary-container': '#e29100',
        'surface-container-highest': '#e1e3e4',
        'on-secondary-fixed': '#00201d',
        'on-primary-fixed': '#002113',
        'surface-tint': '#006c49',
        tertiary: '#855300',
        'surface-dim': '#d9dadb',
        'on-tertiary-fixed-variant': '#653e00',
        'on-primary-fixed-variant': '#005236',
        'on-primary-container': '#00422b',
        secondary: '#006a61',
        /* P2 named aliases (same Stitch values) */
        accent: '#e29100',
        danger: '#ba1a1a',
        success: '#10b981',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        card: '0.75rem',
        'card-inner': '0.5rem',
        pill: '9999px',
        message: '1rem',
      },
      spacing: {
        xl: '32px',
        md: '16px',
        'margin-mobile': '20px',
        base: '4px',
        sm: '12px',
        xs: '8px',
        lg: '24px',
        'gutter-mobile': '16px',
        safe: 'max(12px, env(safe-area-inset-bottom, 0px))',
      },
      height: {
        safe: 'max(12px, env(safe-area-inset-bottom, 0px))',
      },
      scale: {
        98: '0.98',
      },
      fontFamily: {
        brand: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'label-sm': ['Manrope', 'sans-serif'],
        caption: ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        h3: ['Manrope', 'sans-serif'],
        h2: ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        h1: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        h3: ['20px', { lineHeight: '28px', fontWeight: '600' }],
        h2: ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        h1: ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      backgroundImage: {
        'gradient-primary':
          'linear-gradient(135deg, #006c49 0%, #006a61 45%, #00422b 100%)',
      },
    },
  },
  plugins: [],
};
